<h2>Enter Your DB Credentials</h2>
	<?php echo $this->tag->form(array("data/listtabledata", "class"=>"form-horizontal", "role"=>"form")) ?>
	    <div class="form-group">
	      <label class="control-label col-sm-2" for="db">Database:</label>
	      <div class="col-sm-10">          
	        <input type="text" class="form-control" id="db" placeholder="Enter Database Name" name="db" required="required">
	      </div>
	    </div>
	    <div class="form-group">        
	      <div class="col-sm-offset-2 col-sm-10">
	        <button type="submit" class="btn btn-default">Submit</button>
	      </div>
	    </div>
	</form>