<h2>Enter Credentials</h2>
	<?php echo $this->tag->form(array("data/index", "class"=>"form-horizontal", "role"=>"form")) ?>
	    <div class="form-group">
	      <label class="control-label col-sm-2" for="db">Username:</label>
	      <div class="col-sm-10">          
	        <input type="text" class="form-control" id="uname" placeholder="Enter User Name" name="uname" required="required">
	      </div>
	    </div>
	    <div class="form-group">
	      <label class="control-label col-sm-2" for="db">Password:</label>
	      <div class="col-sm-10">          
	        <input type="password" class="form-control" id="pwd" placeholder="Enter Password" name="pwd" required="required">
	      </div>
	    </div>
	    <div class="form-group">        
	      <div class="col-sm-offset-2 col-sm-10">
	        <button type="submit" class="btn btn-default">Submit</button>
	      </div>
	    </div>
	</form>